name: Deploy to cPanel via FTP

on:
    push:
        branches:
            - med

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.techseba.com
          username: med@med.techseba.com
          password: med_ecom_techseba
          port: 21
          server-dir: med.techseba.com/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*
            **/node_modules/**
            **/vendor/**
            **/.env
